name: DataThespian
settings:
  LINT_MODE: ${LINT_MODE}
packages:
  DataThespian:
    path: .
aggregateTargets:
  Lint:
    buildScripts:
      - path: Scripts/lint.sh
        name: Lint
        basedOnDependencyAnalysis: false
    schemes: {}
targets:
  DataThespianExample:
    type: application
    platform: macOS
    dependencies:
      - package: DataThespian
        product: DataThespian
    sources:
      - path: "Example/Sources"
      - path: "Example/Support"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.demo.DataThespianExample
    info:
      path: Example/Support/Info.plist
      properties:
        CFBundlePackageType: APPL
        ITSAppUsesNonExemptEncryption: false
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)